---
apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes-first
  namespace: kustomization
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: hello-kubernetes-first
